export const FALLBACK_ERROR_MSG =
  "An error has occurred while trying to complete your request.";

export const SITE_NAME = "Motordepo.hu";

export const IMAGE_SIZES = {
  245: "thumbnail",
  500: "small",
  750: "medium",
  1000: "large",
};

export const MARKA = [
  { name: "ADIVA", value: "adiva" },
  { name: "ADLY", value: "adly" },
  { name: "AERMACCHI", value: "aermacchi" },
  { name: "AEON", value: "aeon" },
  { name: "AMERIGO", value: "amerigo" },
  { name: "APOLLO", value: "apollo" },
  { name: "APRILIA", value: "aprilia" },
  { name: "ARCTIC CAT", value: "arctic-cat" },
  { name: "ARGO", value: "argo" },
  { name: "ATK", value: "atk" },
  { name: "ATV", value: "atv" },
  { name: "BABETTA", value: "babetta" },
  { name: "BAJAJ", value: "bajaj" },
  { name: "BAOTIAN", value: "baotian" },
  { name: "BASHAN", value: "bashan" },
  { name: "BAZUKA", value: "bazuka" },
  { name: "BENELLI", value: "benelli" },
  { name: "BERVA", value: "berva" },
  { name: "BETAMOTOR", value: "betamotor" },
  { name: "BIMOTA", value: "bimota" },
  { name: "BMW", value: "bmw" },
  { name: "BOMBARDIER", value: "bombardier" },
  { name: "BOOM-TRIKES", value: "boom-trikes" },
  { name: "BOSS", value: "boss" },
  { name: "BRIXTON", value: "brixton" },
  { name: "BSA", value: "bsa" },
  { name: "BSE", value: "bse" },
  { name: "BUELL", value: "buell" },
  { name: "CAGIVA", value: "cagiva" },
  { name: "CAN-AM", value: "can-am" },
  { name: "CCM", value: "ccm" },
  { name: "CCW", value: "ccw" },
  { name: "CECTEK", value: "cectek" },
  { name: "CFMOTO", value: "cfmoto" },
  { name: "CHANG-JIANG", value: "chang-jiang" },
  { name: "CIMATTI", value: "cimatti" },
  { name: "CITIWELL", value: "citiwell" },
  { name: "CPI", value: "cpi" },
  { name: "CZ", value: "cz" },
  { name: "CSEPEL", value: "csepel" },
  { name: "DAELIM", value: "daelim" },
  { name: "DANUVIA", value: "danuvia" },
  { name: "DAYTONA", value: "daytona" },
  { name: "DB", value: "db" },
  { name: "DERBI", value: "derbi" },
  { name: "DI", value: "di" },
  { name: "DINLI", value: "dinli" },
  { name: "DKW", value: "dkw" },
  { name: "DNEPR", value: "dnepr" },
  { name: "DONGÓ", value: "dongo" },
  { name: "DUCATI", value: "ducati" },
  { name: "E-MAX", value: "e-max" },
  { name: "E-TON", value: "e-ton" },
  { name: "EGYEDI", value: "egyedi" },
  { name: "EGYÉB", value: "egyeb" },
  { name: "EXPLORER", value: "explorer" },
  { name: "FACTORY", value: "factory" },
  { name: "FANTIC MOTOR", value: "fantic-motor" },
  { name: "FOSTI", value: "fosti" },
  { name: "FUTONG", value: "futong" },
  { name: "GARELLI", value: "garelli" },
  { name: "GAS GAS", value: "gas-gas" },
  { name: "GENERIC", value: "generic" },
  { name: "GILERA", value: "gilera" },
  { name: "GOES", value: "goes" },
  { name: "HARLEY DAVIDSON", value: "harley-davidson" },
  { name: "HECHT", value: "hecht" },
  { name: "HERCULES", value: "hercules" },
  { name: "HERKULES", value: "herkules" },
  { name: "HISUN", value: "hisun" },
  { name: "HONDA", value: "honda" },
  { name: "HOREX", value: "horex" },
  { name: "HUSABERG", value: "husaberg" },
  { name: "HUSQVARNA", value: "husqvarna" },
  { name: "HYOSUNG", value: "hyosung" },
  { name: "IMR", value: "imr" },
  { name: "INDIAN", value: "indian" },
  { name: "IO", value: "io" },
  { name: "ITALJET", value: "italjet" },
  { name: "IZH", value: "izh" },
  { name: "IZS", value: "izs" },
  { name: "JAWA", value: "jawa" },
  { name: "JET MOTO", value: "jet-moto" },
  { name: "JINCHENG", value: "jincheng" },
  { name: "JINLING", value: "jinling" },
  { name: "JINLUN", value: "jinlun" },
  { name: "JONWAY", value: "jonway" },
  { name: "JUNAK", value: "junak" },
  { name: "KAWADA", value: "kawada" },
  { name: "KAWASAKI", value: "kawasaki" },
  { name: "KAYAK", value: "kayak" },
  { name: "KAZUMA", value: "kazuma" },
  { name: "KEEWAY", value: "keeway" },
  { name: "KINROAD", value: "kinroad" },
  { name: "KREIDLER", value: "kreidler" },
  { name: "KSR MOTO", value: "ksr-moto" },
  { name: "KTM", value: "ktm" },
  { name: "KUBA", value: "kuba" },
  { name: "KUMPAN-ELECTRIC", value: "kumpan-electric" },
  { name: "KXD ", value: "kxd" },
  { name: "KYMCO", value: "kymco" },
  { name: "LAMBRETTA", value: "lambretta" },
  { name: "LAVERDA", value: "laverda" },
  { name: "LASER", value: "laser" },
  { name: "LEM", value: "lem" },
  { name: "LIFAN", value: "lifan" },
  { name: "LIGIER", value: "ligier" },
  { name: "LINEA", value: "linea" },
  { name: "LINGYUN", value: "lingyun" },
  { name: "LINHAI", value: "linhai" },
  { name: "LML", value: "lml" },
  { name: "LONCIN", value: "loncin" },
  { name: "LONGBO", value: "longbo" },
  { name: "MAGNI", value: "magni" },
  { name: "MALAGUTI", value: "malaguti" },
  { name: "MALANCA", value: "malanca" },
  { name: "MASAI", value: "masai" },
  { name: "MASH", value: "mash" },
  { name: "MATCHLESS", value: "matchless" },
  { name: "MBK", value: "mbk" },
  { name: "MEX", value: "mex" },
  { name: "MONDIAL", value: "mondial" },
  { name: "MOTO GUZZI", value: "moto-guzzi" },
  { name: "MOTO MORINI", value: "moto-morini" },
  { name: "MOTOBI", value: "motobi" },
  { name: "MOTOM", value: "motom" },
  { name: "MOTORHISPANIA", value: "motorhispania" },
  { name: "MOTORRO", value: "motorro" },
  { name: "MOTOWELL", value: "motowell" },
  { name: "MV AGUSTA", value: "mv-agusta" },
  { name: "MZ", value: "mz" },
  { name: "NITRO", value: "nitro" },
  { name: "NIU", value: "niu" },
  { name: "NORTON", value: "norton" },
  { name: "NSU", value: "nsu" },
  { name: "OMI", value: "omi" },
  { name: "ORION", value: "orion" },
  { name: "PANNONIA", value: "pannonia" },
  { name: "PEDA", value: "peda" },
  { name: "PEUGEOT", value: "peugeot" },
  { name: "PGO", value: "pgo" },
  { name: "PIAGGIO", value: "piaggio" },
  { name: "POLARIS", value: "polaris" },
  { name: "POLINI", value: "polini" },
  { name: "POLYMOBIL", value: "polymobil" },
  { name: "PUCH", value: "puch" },
  { name: "QINGQI", value: "qingqi" },
  { name: "QLINK", value: "qlink" },
  { name: "QM", value: "qm" },
  { name: "REGAL-RAPTOR", value: "regal-raptor" },
  { name: "REX", value: "rex" },
  { name: "RIDE", value: "ride" },
  { name: "RIEJU", value: "rieju" },
  { name: "RIGA", value: "riga" },
  { name: "ROMET", value: "romet" },
  { name: "ROYAL ENFIELD", value: "royal-enfield" },
  { name: "SACHS", value: "sachs" },
  { name: "SECMA", value: "secma" },
  { name: "SHERCO", value: "sherco" },
  { name: "SHINERAY", value: "shineray" },
  { name: "SIAMOTO", value: "siamoto" },
  { name: "SILENCE", value: "silence" },
  { name: "SIMSON", value: "simson" },
  { name: "SOLEX", value: "solex" },
  { name: "SONIK", value: "sonik" },
  { name: "SUKIDA", value: "sukida" },
  { name: "SUPER SOCO", value: "super-soco" },
  { name: "SUR-RON", value: "sur-ron" },
  { name: "SUZUKI", value: "suzuki" },
  { name: "SWM", value: "swm" },
  { name: "SYM", value: "sym" },
  { name: "TAURIS", value: "tauris" },
  { name: "TGB", value: "tgb" },
  { name: "TM", value: "tm" },
  { name: "TOMOS", value: "tomos" },
  { name: "TORROT", value: "torrot" },
  { name: "TRIUMPH", value: "triumph" },
  { name: "URAL", value: "ural" },
  { name: "VERHOVINA", value: "verhovina" },
  { name: "VERVEMOTO", value: "vervemoto" },
  { name: "VESPA", value: "vespa" },
  { name: "VICTORY", value: "victory" },
  { name: "VOGE", value: "voge" },
  { name: "VOR", value: "vor" },
  { name: "WEXXTOR", value: "wexxtor" },
  { name: "WUYANG", value: "wuyang" },
  { name: "XMOTOS", value: "xmotos" },
  { name: "YAMAHA", value: "yamaha" },
  { name: "YIYING", value: "yiying" },
  { name: "YOMOTO", value: "yomoto" },
  { name: "Z-TECH", value: "z-tech" },
  { name: "ZERO", value: "zero" },
  { name: "ZHONGYU", value: "zhongyu" },
  { name: "ZIPP", value: "zipp" },
  { name: "ZNEN", value: "znen" },
  { name: "ZONGSHEN", value: "zongshen" },
  { name: "ZÜNDAPP", value: "zundapp" },
];
export const KIVITEL = [
  "Cruiser, Chopper, Custom",
  "Elektromos",
  "Enduro",
  "Gyerekmotor",
  "Gyorsasági, Sport",
  "Robogó",
  "Nagyrobogó",
  "Oldalkocsis",
  "Quad",
  "Segédmotoros kerékpár, moped",
  "Streetfighter",
  "Supermoto",
  "Trial",
  "Trike",
  "Túra (Naked, Túra sport, Túra Enduro)",
  "Versenymotor, Pályamotor",
  "Veterán",
  "Egyéb",
];
export const MUNKAUTEM = ["2", "4"];
export const SEBESSEGVALTO = ["Manuális", "Automata"];
export const ALLAPOT = [
  "Normál",
  "Megkimélt",
  "Kitűnő",
  "Sérülésmentes",
  "Sérült",
  "Hibás",
  "Hiányos",
];
export const OKMANYOK = [
  "Érvényes magyar okmányokkal",
  "Lejárt magyar okmányokkal",
  "Külföldi okmányokkal",
  "Okmányok nélkül",
];
export const EGYEB = [
  "Garanciális",
  "Azonnal elvihető",
  "Motorbeszámítás lehetséges",
  "Szervizkönyv",
];
